<%@ Page Language="C#" MasterPageFile="~/moudle/MasterPage.master" AutoEventWireup="true" CodeFile="ADDGOU.aspx.cs" Inherits="ADDGOU1" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <div style="z-index: 101; left: 78px; width: 100px; position: absolute; top: 0px;
        height: 100px">
        <asp:UpdatePanel id="UpdatePanel1" runat="server">
            <contenttemplate>
<TABLE style="WIDTH: 343px; HEIGHT: 354px" border=0><TR><TD style="FONT-SIZE: 12px; COLOR: black; BORDER-TOP-STYLE: none; BORDER-RIGHT-STYLE: none; BORDER-LEFT-STYLE: none; HEIGHT: 19px; BACKGROUND-COLOR: #7ec3bf; TEXT-ALIGN: center; BORDER-BOTTOM-STYLE: none" align=center colSpan=3>购入信息</TD></TR><TR><TD style="WIDTH: 90px; HEIGHT: 13px">日期：</TD><TD style="WIDTH: 234px; HEIGHT: 13px" colSpan=2><asp:TextBox id="time" runat="server" Width="129px"></asp:TextBox> <asp:RequiredFieldValidator id="RequiredFieldValidator1" runat="server" ControlToValidate="time" ErrorMessage="日期不能为空！" ValidationGroup="2">日期不能为空！</asp:RequiredFieldValidator></TD></TR><TR style="COLOR: #4f6b72"><TD style="WIDTH: 90px; HEIGHT: 10px">矿名：</TD><TD style="WIDTH: 234px; HEIGHT: 10px" colSpan=2><asp:DropDownList id="K_name" runat="server">
                    </asp:DropDownList> &nbsp;&nbsp; </TD></TR><TR><TD style="WIDTH: 90px; HEIGHT: 3px">数量：</TD><TD style="WIDTH: 234px; HEIGHT: 3px" colSpan=2><asp:TextBox id="amount" runat="server" Width="107px">0</asp:TextBox> <asp:RequiredFieldValidator id="RequiredFieldValidator2" runat="server" ControlToValidate="amount" ErrorMessage="数量不能为空！" ValidationGroup="2">数量不能为空！</asp:RequiredFieldValidator> <asp:RequiredFieldValidator id="RequiredFieldValidator3" runat="server" ControlToValidate="amount" ErrorMessage="计算总额的时候，数量不能为空！" ValidationGroup="1">计算总额的时候，数量不能为空！</asp:RequiredFieldValidator></TD></TR><TR><TD style="WIDTH: 90px; HEIGHT: 15px">单价：</TD><TD style="WIDTH: 234px; HEIGHT: 15px" colSpan=2><asp:TextBox id="price" runat="server" Width="107px">0</asp:TextBox> &nbsp; &nbsp; <asp:Button id="Button3" onclick="Button3_Click" runat="server" Width="61px" ValidationGroup="1" Text="计算总额"></asp:Button> <asp:RequiredFieldValidator id="jstotal" runat="server" ControlToValidate="price" ErrorMessage="要计算总额，单价不能为空！" ValidationGroup="1">要计算总额，单价不能为空！</asp:RequiredFieldValidator></TD></TR><TR><TD style="WIDTH: 90px; HEIGHT: 8px">总额：</TD><TD style="WIDTH: 234px; HEIGHT: 8px" colSpan=2><asp:TextBox id="total" runat="server" Width="107px" ForeColor="Red">0</asp:TextBox> <asp:DropDownList id="djs" runat="server">
                        <asp:ListItem Value="2">已结算</asp:ListItem>
                        <asp:ListItem Selected="True" Value="1">未结算</asp:ListItem>
                    </asp:DropDownList></TD></TR><TR><TD style="WIDTH: 90px; HEIGHT: 8px">票据：</TD><TD style="WIDTH: 234px; HEIGHT: 8px" colSpan=2><asp:TextBox id="billno" runat="server" Width="105px"></asp:TextBox></TD></TR><TR><TD style="WIDTH: 90px; HEIGHT: 8px">已付款：</TD><TD style="WIDTH: 234px; HEIGHT: 8px" colSpan=2><asp:TextBox id="yfk" runat="server" Width="103px"></asp:TextBox></TD></TR><TR><TD style="WIDTH: 90px; HEIGHT: 40px">备注：</TD><TD style="WIDTH: 234px" colSpan=2><asp:TextBox id="remark" runat="server" Width="223px" Height="95px" Rows="3" TextMode="MultiLine"></asp:TextBox></TD></TR><TR><TD style="WIDTH: 90px; HEIGHT: 12px">操作员：</TD><TD style="WIDTH: 234px; HEIGHT: 12px" colSpan=2><asp:Label id="user" runat="server" Width="93px" Text="Label" ForeColor="Red"></asp:Label></TD></TR><TR><TD style="HEIGHT: 36px" align=center colSpan=3><asp:Button id="Button1" onclick="Button1_Click" runat="server" Width="60px" ValidationGroup="2" Text="添加"></asp:Button><asp:Button id="Button4" onclick="Button4_Click" runat="server" Width="65px" ValidationGroup="2" Text="更新"></asp:Button></TD></TR></TABLE>
</contenttemplate>
        </asp:UpdatePanel></div>
</asp:Content>

