<%@ Page Language="C#" MasterPageFile="~/moudle/MasterPage.master" AutoEventWireup="true" CodeFile="ADDxiao.aspx.cs" Inherits="ADDxiao" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
 <asp:UpdatePanel id="UpdatePanel1" runat="server">
     <ContentTemplate>
<DIV style="Z-INDEX: 101; LEFT: 64px; WIDTH: 168px; POSITION: absolute; TOP: 0px; HEIGHT: 100px"><TABLE style="WIDTH: 388px; HEIGHT: 310px" id="TABLE1" border=0><TBODY><TR><TD style="FONT-SIZE: 12px; COLOR: black; BORDER-TOP-STYLE: none; BORDER-RIGHT-STYLE: none; BORDER-LEFT-STYLE: none; HEIGHT: 19px; BACKGROUND-COLOR: #7ec3bf; TEXT-ALIGN: center; BORDER-BOTTOM-STYLE: none" align=center colSpan=2>销（添加记录）</TD></TR><TR><TD style="WIDTH: 81px; HEIGHT: 0px">日期：</TD><TD style="WIDTH: 108px; HEIGHT: 0px"><asp:TextBox id="time" runat="server" Width="99px"></asp:TextBox>&nbsp; <DIV style="Z-INDEX: 108; LEFT: 251px; WIDTH: 26px; POSITION: absolute; TOP: 41px; HEIGHT: 2px"><asp:RequiredFieldValidator id="RequiredFieldValidator2" runat="server" Width="95px" ValidationGroup="ok" Height="1px" ErrorMessage="日期不能为空！" ControlToValidate="time">日期不能为空！</asp:RequiredFieldValidator></DIV><SPAN style="FONT-SIZE: 9pt; COLOR: #3399cc"></SPAN></TD></TR><TR><TD style="WIDTH: 81px; HEIGHT: 0px">车号：</TD><TD style="WIDTH: 108px; HEIGHT: 0px"><asp:TextBox id="carno" runat="server"></asp:TextBox>&nbsp; <DIV style="Z-INDEX: 106; LEFT: 290px; WIDTH: 36px; POSITION: absolute; TOP: 80px; HEIGHT: 1px"><asp:RequiredFieldValidator id="RequiredFieldValidator3" runat="server" Width="87px" ValidationGroup="ok" Height="1px" ErrorMessage="车号不能为空！" ControlToValidate="carno">车号不能为空！</asp:RequiredFieldValidator></DIV></TD></TR><TR><TD style="WIDTH: 81px; HEIGHT: 0px">凭证号：</TD><TD style="WIDTH: 108px; HEIGHT: 0px"><asp:TextBox id="voucher" runat="server"></asp:TextBox> <DIV style="Z-INDEX: 107; LEFT: 295px; WIDTH: 10px; POSITION: absolute; TOP: 119px; HEIGHT: 6px"><asp:RequiredFieldValidator id="RequiredFieldValidator4" runat="server" Width="114px" ValidationGroup="ok" Height="14px" ErrorMessage="凭证号不能为空！" ControlToValidate="voucher">凭证号不能为空！</asp:RequiredFieldValidator></DIV></TD></TR><TR><TD style="WIDTH: 81px; HEIGHT: 0px">销售单位：</TD><TD style="WIDTH: 108px; HEIGHT: 0px"><asp:DropDownList id="client" runat="server" DataValueField="gy_clientID" DataTextField="gy_c_name" DataSourceID="SqlDataSource1">
                    </asp:DropDownList>&nbsp; </TD></TR><TR><TD style="WIDTH: 81px; HEIGHT: 0px">数量：</TD><TD style="WIDTH: 108px; HEIGHT: 0px"><asp:TextBox id="amount" runat="server"></asp:TextBox>&nbsp; <DIV style="Z-INDEX: 101; LEFT: 305px; WIDTH: 42px; POSITION: absolute; TOP: 195px; HEIGHT: 13px"><asp:RequiredFieldValidator id="RequiredFieldValidator5" runat="server" Width="173px" ValidationGroup="total" Height="10px" ErrorMessage="计算总额时，数量不能为空！" ControlToValidate="amount">计算总额时，数量不能为空！</asp:RequiredFieldValidator> <asp:RequiredFieldValidator id="RequiredFieldValidator6" runat="server" Width="157px" ValidationGroup="ok" Height="8px" ErrorMessage="数量不能为空！" ControlToValidate="amount">数量不能为空！</asp:RequiredFieldValidator></DIV></TD></TR><TR><TD style="WIDTH: 81px; HEIGHT: 0px">单价：</TD><TD style="WIDTH: 108px; HEIGHT: 0px"><asp:TextBox id="price" runat="server" Width="102px">0</asp:TextBox></TD></TR><TR><TD style="WIDTH: 81px; HEIGHT: 0px">总额：</TD><TD style="WIDTH: 108px; HEIGHT: 0px"><asp:TextBox id="total" runat="server" ForeColor="#C00000">0</asp:TextBox> <DIV style="Z-INDEX: 103; LEFT: 261px; WIDTH: 100px; POSITION: absolute; TOP: 231px; HEIGHT: 25px"><asp:Button id="Button1" onclick="Button1_Click" runat="server" ValidationGroup="total" Text="计算总额"></asp:Button> <asp:RequiredFieldValidator id="RequiredFieldValidator1" runat="server" Width="1px" ValidationGroup="total" Height="7px" ErrorMessage="计算总额时，单价不能为空。" ControlToValidate="price">*</asp:RequiredFieldValidator></DIV></TD></TR><TR><TD style="WIDTH: 81px; HEIGHT: 0px">操作员：</TD><TD style="WIDTH: 108px; HEIGHT: 0px"><asp:Label id="user" runat="server">Label</asp:Label>&nbsp; <DIV style="Z-INDEX: 109; LEFT: 201px; WIDTH: 39px; POSITION: absolute; TOP: 305px; HEIGHT: 9px"><asp:DropDownList id="DropDownList1" runat="server">
                            <asp:ListItem Value="2">已结算</asp:ListItem>
                            <asp:ListItem Selected="True" Value="1">未结算</asp:ListItem>
                        </asp:DropDownList></DIV></TD></TR><TR><TD style="WIDTH: 81px; HEIGHT: 0px">备注：</TD><TD style="WIDTH: 108px; HEIGHT: 0px"><asp:TextBox id="remark" runat="server" Width="224px" Height="87px" TextMode="MultiLine" Rows="4"></asp:TextBox></TD></TR><TR><TD style="HEIGHT: 3px" align=center colSpan=2><asp:Button id="botton2" onclick="botton2_Click" runat="server" Width="61px" ValidationGroup="ok" Text="添加"></asp:Button> <asp:Button id="botton3" onclick="botton3_Click" runat="server" Width="61px" Text="更新" CausesValidation="False"></asp:Button> </TD></TR></TBODY></TABLE><DIV style="Z-INDEX: 104; LEFT: 393px; WIDTH: 100px; POSITION: absolute; TOP: 360px; HEIGHT: 100px">&nbsp;<asp:SqlDataSource id="SqlDataSource1" runat="server" SelectCommand="SELECT [gy_clientID], [gy_c_name] FROM [gy_client]" ProviderName="System.Data.SqlClient" ConnectionString="Data Source=.\SqlExpress;Initial Catalog=DbName;User ID=sa;pwd=sa;">
            </asp:SqlDataSource> </DIV><DIV style="Z-INDEX: 105; LEFT: 399px; WIDTH: 100px; POSITION: absolute; TOP: 241px; HEIGHT: 100px"><asp:ValidationSummary id="ValidationSummary1" runat="server" Width="141px" ValidationGroup="total" Height="38px" ShowSummary="False" ShowMessageBox="True"></asp:ValidationSummary> <asp:ValidationSummary id="ValidationSummary2" runat="server" Width="140px" ValidationGroup="ok" Height="1px" ShowSummary="False" ShowMessageBox="True"></asp:ValidationSummary> </DIV></DIV>
</ContentTemplate>
      </asp:UpdatePanel>
   </asp:Content>

